name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Package
        run: zip -r "1pp_hq_music_II_${GITHUB_REF_NAME}".zip 1pp_hq_music_II setup-1pp_hq_music_II.exe

      - name: GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: "1pp_hq_music_II_${GITHUB_REF_NAME}.zip"
